package by.htp.it.controller;

public enum CommandName {

	GO_TO_AUTHORIZATION_PAGE, GO_TO_REGISTRATION_PAGE, SIGN_IN, UNKNOWN_COMMAND, REGISTRATION_NEW_USER, GO_TO_MAIN_PAGE,
	ADD_NEWS, LOG_OUT, GO_TO_ADD_NEWS_PAGE, CHANGE_LOCALE, DELETE_NEWS, READ_NEWS, ADD_TO_FAVORITES,
	DELETE_FROM_FAVORITES, EDIT_NEWS, GO_TO_EDIT_NEWS_PAGE, READ_ALL_NEWS, OPEN_PROFILE, VIEW_FAVORITE_NEWS,
	ADD_COMMENT, OFFER_NEWS, GO_TO_OFFER_NEWS_PAGE, VIEW_USER_OFFERED_NEWS, VIEW_OFFERED_NEWS, DENY_TO_PUBLISH,
	GO_TO_CHECK_OFFERED_NEWS_PAGE, APPROVE_PUBLICATION, GO_TO_CHANGE_PASSWORD_PAGE, CHANGE_PASSWORD;

}